### ISSUE TITLE
allureReporter.NightwatchAllureReporter is not a constructor

### ISSUE THREAD

**Issue by phaseen** [kushmangal/Nightwatch-Allure-Reporter#6] opened 2020-04-14 01:56 UTC
I am seeing this error when I added below lines to globals.js file, I am I missing some thing? iam using latest package  1.2.0

const allureReporter = require('nightwatch-allure');
module.exports = {
  reporter: (results, done) => {
    const reporter = new allureReporter.NightwatchAllureReporter({});
    reporter.write(results, done);
  },
}

   TypeError: allureReporter.NightwatchAllureReporter is not a constructor
       at Object.reporter (/Users/xyz/UITest/src/UITest/src/UITest/globals.js:30:22)
       at new Promise (<anonymous>)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by kushmangal** [comment] 2020-04-14 16:21
Hey @phaseen, I am not able to reproduce it. Can you share with me your package.json file?
If you could share your test snippet, then it can even help me resolve this lot more sooner.
You can share those to my email kushagra12mangal@gmail.com

**Comment by phaseen** [comment] 2020-04-14 17:29
I sent you the details.

**Comment by kushmangal** [comment] 2020-10-28 19:37
Hey @phaseen as I was not able to get the snippet and am not able to reproduce the bug at the moment. I will be closing the issue. Please open if you are able to generate a snippet with this issue occurring. Thanks for reporting

**Closed as completed by kushmangal** 2020-10-28 19:37 UTC
Labels: bug
